### ISSUE TITLE
Color scheme and Front end JavaScript

### ISSUE THREAD

**Issue by jbryant4** [jbryant4/Project2-Group1#9]
Helping out on the front end JavaScript. and giving team ideas for color schemes. Will refer to the just tech news.

**Comment by lilyhi** [comment]
Color scheme ideas:

[One](https://colorhunt.co/palette/04009a77acf13edbf0f0ebcc)

[Two](https://colorhunt.co/palette/413c694a47a3709fb0a7c5eb)

[Three](https://colorhunt.co/palette/f6f6f6c7ffd898ded9161d6f)

[Four](https://colorhunt.co/palette/006a71ffffddcbeaedd3de32)

[Five](https://colorhunt.co/palette/09253289c9b8c7e2b2e1ffc2)

[Six](https://colorhunt.co/palette/8adfdc3138487353728f758e)

[Seven](https://colorhunt.co/palette/222831393e46b55400eeeeee)

[Eight](https://colorhunt.co/palette/04009a77acf13edbf0c0fefc)

[Nine](https://colorhunt.co/palette/f2f4f61ee3cf6b48ff0d3f67)
